spring:
  application:
    name: systock

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/systock}
    username: ${DB_USER:systock}
    password: ${DB_PASSWORD:systock_dev}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: when-authorized

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never

systock:
  crypto:
    secret-key: ${b43135798b3b053e65487699f5e30f80}

logging:
  level:
    root: INFO
    com.systock: DEBUG
    org.springframework.security: INFO
